### ISSUE TITLE
[RF] Pep8ify code thoroughly

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#471]

**Comment by tsalo** [comment]
To that end, here are a few steps that I think need to be taken:

- [ ] Replace relative imports with absolute ones. Addressed in #472.
- [ ] Replace %-formatted and `.format`-formatted strings with f-strings. Addressed in #473.
- [ ] Sort imports. I'm waiting until #472 is merged to do this.
- [ ] Remove any unused imports and variables.
- [ ] Ensure all classes are named according to UpperCamelCase and all functions are snake_case.
